### PR TITLE
Minor tweaks applied

### PR DESCRIPTION
**Pull request by leo**
Awesome package! 😊 Here are a few tweaks to make it even better.

### CODE REVIEW

**Comment by samjbmason** [comment]
Is there any chance of this getting merged and released soon? @pedronauck

**Comment by samjbmason** [comment]
Actually it looks like after installing @leo forked version that this PR is based on it actually breaks micro-router but not sending a response

**Comment by samjbmason** [comment]
Ignore my comments above this has been solved with micro#16

**Comment by leo** [comment]
@pedronauck Why did you close this?

**Comment by pedronauck** [comment]
Sorry @leo, I closed the wrong thing 😂

**Pull request merged**
