### PR TITLE
nested routing

### PR DESCRIPTION
**Pull request by ppot**
Add Router object.
Add Route object.
Update route testing.

Allow nesting. and easy composition.
Use the default `methodFn` and async functions.

### CODE REVIEW

**Comment by ppot** [comment]
@pedronauck Any take on this?

**Comment by MarkusPfundstein** [comment]
This is adding pretty nice functionality actually. It'd be great if @pedronauck could attend to it. @ppot You should fix the linter issues (Codacy) and decreased coverage though.

**Comment by ppot** [comment]
Ya, once he give is take on this

**Comment by pedronauck** [comment]
Sorry, I didn't  accept your pull request because one of the premises of the project is it more functional, so I think that isn't a good thing make features using classes. By the way, in the [new version](https://github.com/pedronauck/micro-router/releases/tag/v3.1.0) you can create nested routes using the [withNamespace](https://github.com/pedronauck/micro-router#namespaced-routes) function

**Comment by ppot** [comment]
@pedronauck It's totally ok. As long as we can now ;)

**Pull request closed without merging**
